resources:
- manager.yaml

patches:
  - patch: |
      - op: replace
        path: '/spec/template/spec/containers/0/image'
        value: '${RELEASE_REGISTRY}/crd-scenarios-operator:${CHART_APPVERSION}'
    target:
      kind: Deployment
      name: lifecycle-operator
      namespace: system
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - name: controller
    newName: docker.io/mowies/crd-scenarios-operator
    newTag: v1
