apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-metrics-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: crd-scenarios
    app.kubernetes.io/part-of: crd-scenarios
  {{- include "chart.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get