# permissions for end users to view books.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: book-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-scenarios
    app.kubernetes.io/part-of: crd-scenarios
    app.kubernetes.io/managed-by: kustomize
  name: book-viewer-role
rules:
- apiGroups:
  - store.test.keptn.sh
  resources:
  - books
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - store.test.keptn.sh
  resources:
  - books/status
  verbs:
  - get
