---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - store.test.keptn.sh
  resources:
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.test.keptn.sh
  resources:
  - books/finalizers
  verbs:
  - update
- apiGroups:
  - store.test.keptn.sh
  resources:
  - books/status
  verbs:
  - get
  - patch
  - update
