# permissions for end users to edit boxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: box-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-scenarios
    app.kubernetes.io/part-of: crd-scenarios
    app.kubernetes.io/managed-by: kustomize
  name: box-editor-role
rules:
- apiGroups:
  - storage.test.keptn.sh
  resources:
  - boxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.test.keptn.sh
  resources:
  - boxes/status
  verbs:
  - get
